In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('fil-t3.csv')

In [6]:
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,جدول رقم (33): قيم أصول الصناديق الخاصة مصنفة ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(مليون ريال)\n (Million Riyals)
5,نهاية الفترة,أسهم,أدوات دين,أسواق نقد,عقاري,متعدد الأصول,التحوط \nوالمشتقات المالية,مغذي,تمويلي,أسهم الملكية الخاصة,رأس المال الجريء,وقفي,سلع,الإجمالي
6,End of Period,Equities,Debt Instruments,Money Markets,Real Estates,Multi-assets,Hedging and Other Derivatives,Feeder Fund,Credit Base Fund,Private equity,Venture capital,Endowment Investment,Commodities,Total
7,النصف الأول عام 2013م\nFirst half 2013,10865.07,10.4,420.39,17733.25,571.21,2323.87,-,-,-,-,-,47.85,31972.04
8,النصف الثاني عام 2013م\nSecond half 2013,11536.9,4.2,608.5,21437.2,602,2404.9,-,-,-,-,-,50.7,36644.4
9,النصف الأول عام 2014م\nFirst half 2014,13337.08,3.03,868.37,30917.56,538.94,2522.65,-,-,-,-,-,47.44,48235.07
10,النصف الثاني عام 2014م\nSecond half 2014,13667.79,126.21,1688.74,33068.11,506.48,2329.07,-,-,-,-,-,46.8,51433.2
11,النصف الأول عام 2015م\nFirst half 2015,13771.24,410.02,1783.46,35109.37,409.03,2470,-,-,-,-,-,247.11,54200.23
12,الربع الثالث عام 2015م\nThird quarter 2015,22943,412.38,1952.17,42879.45,496.33,2284.19,-,-,-,-,-,252.53,71220.05
13,الربع الرابع عام 2015م\nFourth quarter 2015,23499.24,3085.04,1725.27,45466.75,1145.78,2220.22,-,-,-,-,-,252.23,77394.53
14,الربع الأول عام 2016م\nFirst quarter 2016,25845.3961622,3092.705883,1603.82495235,39839.564976,1114.69849421,1960.32897463,-,-,-,-,-,300.989934113,73757.5093765
15,الربع الثاني عام 2016م\nSecond quarter 2016,26234.5179952,3077.21098765,1257.79677949,44042.5062973,1133.71422049,1497.6101044,-,-,-,-,-,317.461092224,77560.8174767
16,الربع الثالث عام 2016م\nThird quarter 2016,27417.46,2807.14,1509.39,44965.14,1167.53,1498.48,-,-,-,-,-,317.78,79682.92
17,الربع الرابع عام 2016م\nFourth quarter 2016,62300.49,2801.25,1412.66,54960.08,6207.26,658.16,-,-,-,-,-,325.54,128665.44
18,الربع الأول عام 2017م\nFirst quarter 2017,62166.0207513,2807.428865,1592.94568468,54891.9953597,6459.86557835,661.19,-,-,-,-,-,318.485174845,128897.931414
19,الربع الثاني عام 2017م\nSecond quarter 2017,77137.4548211,4138.762136,1550.34056923,56822.77,8737.87698891,669.956569825,-,-,-,-,-,321.444865589,149378.605951
20,الربع الثالث عام 2017م\nThird quarter 2017,75919.72,4489.85,1626.95,58393.93,6941.12,674.77,-,-,-,-,-,325.9,148372.24
21,الربع الرابع عام 2017م\nFourth quarter 2017,75857.11,4600.53,1674.49,57686.74,816.25,666.31,-,-,-,-,-,332.02,141633.45
22,الربع الأول عام 2018م\nFirst quarter 2018,81683.03,4648.09,1772.75,56673.95,1151.66,571.89,-,-,-,-,-,333.83,146835.2
23,الربع الثاني عام 2018م\nSecond quarter 2018,87241.1600278,4840.79254933,1879.9040905,56717.3018286,746.86723371,579.350131688,-,-,-,-,-,396.86815176,152402.244013
24,الربع الثالث عام 2018م\nThird quarter 2018,99674.6591118,4790.17981933,2160.18964905,57290.0065528,707.22593969,582.671903962,-,-,-,-,-,397.89880521,165602.831782
25,الربع الرابع عام 2018م\nFourth quarter 2018,104603.1,4847.00160756,1164.73496285,58321.42,7027.79417206,578.445343725,0,1280.51645296,-,-,-,456.484813308,178279.497352
26,الربع الأول عام 2019م\nFirst quarter 2019,122620.291142,4727.59184098,2056.5130275,52099.2120501,7403.00028479,568.8375,0,239.60637088,-,-,-,451.567655123,190166.619872
27,الربع الثاني عام 2019م\nSecond quarter 2019,122482.139848,4987.71810867,1879.39461453,58698.2194342,7637.69399755,581.147515387,0,249.191350587,-,-,-,383.935211167,196899.44008
28,الربع الثالث عام 2019م\nThird quarter 2019,108653.591253,4954.65548467,2048.082239,61340.0052916,7028.39950796,576.888293062,132.80680351,287.680524,-,-,-,383.334541761,185405.443939
29,الربع الرابع عام 2019م\nFourth quarter 2019,114501.03,5175.18,2262.26,58458.13,7836.23,325.15,59.75,459.51,-,-,-,382.74,189459.98
30,الربع الأول عام 2020م\nFirst quarter 2020,97081.7317695,5776.97693985,2038.12290354,61474.5958119,6561.55020103,324.459096262,135.36948975,730.416508961,-,-,-,-,174123.222721
31,الربع الثاني عام 2020م\nSecond quarter 2020,104359.418781,10222.0371434,1918.02462321,74006.1043075,7280.70386808,324.459096262,191.445689818,810.178851299,-,-,-,-,199112.372361
32,الربع الثالث عام 2020م\nThird quarter 2020,119296.162156,10307.7863539,2082.37287692,77616.5919898,9349.92484136,331.812897225,247.92319091,757.629,-,-,-,-,219990.203307
33,الربع الرابع عام 2020م\nFourth quarter 2020,125414.03,10708.9,2207.24,83156.98,9269.44,323.13,292.1,879.52,-,-,-,-,232251.34
34,الربع الأول عام 2021م\nFirst quarter 2021,134542.33,11594.61,2228.84,86673.25,10232.6,340.31,333.26,564.6,10523.71,333.02,0,0,257366.53
35,الربع الثاني عام 2021م\nSecond quarter 2021,151433.95,8847.18,2490.68,89073.26,9953.15,350.67,346.25,621.1,10961.02,364.93,0,0,274442.19
36,الربع الثالث عام 2021م\nThird quarter 2021,158999.14,10799.25,2552.79,89527.02,11572.44,350.67,370.19,749.93,11367.49,440.3,0,0,286729.22
37,الربع الرابع عام 2021م\nFourth quarter 2021,160141.02,11411.09,2517.56,96228.08,12039.73,353.85,405.72,794.62,12153.59,552.84,27.8,0,296625.9
38,الربع الأول عام 2022م\nFirst quarter 2022,191950.54,12670.26,2384.44,99133.29,13291.76,-,406.05,710.37,14141.82,710.45,27.8,0,335426.78
39,الربع الثاني عام 2022م\nSecond quarter 2022,170129.7,13009.68,2403.64,113178.38,14636.62,-,361.16,668.91,18198.09,1031.32,28.44,0,333645.94

In [7]:
data.drop([2,3,4,5,6,7])

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,النصف الثاني عام 2013م\nSecond half 2013,11536.9,4.2,608.5,21437.2,602,2404.9,-,-,-,-,-,50.7,36644.4
9,النصف الأول عام 2014م\nFirst half 2014,13337.08,3.03,868.37,30917.56,538.94,2522.65,-,-,-,-,-,47.44,48235.07
10,النصف الثاني عام 2014م\nSecond half 2014,13667.79,126.21,1688.74,33068.11,506.48,2329.07,-,-,-,-,-,46.8,51433.2
11,النصف الأول عام 2015م\nFirst half 2015,13771.24,410.02,1783.46,35109.37,409.03,2470,-,-,-,-,-,247.11,54200.23
12,الربع الثالث عام 2015م\nThird quarter 2015,22943,412.38,1952.17,42879.45,496.33,2284.19,-,-,-,-,-,252.53,71220.05
13,الربع الرابع عام 2015م\nFourth quarter 2015,23499.24,3085.04,1725.27,45466.75,1145.78,2220.22,-,-,-,-,-,252.23,77394.53
14,الربع الأول عام 2016م\nFirst quarter 2016,25845.3961622,3092.705883,1603.82495235,39839.564976,1114.69849421,1960.32897463,-,-,-,-,-,300.989934113,73757.5093765
15,الربع الثاني عام 2016م\nSecond quarter 2016,26234.5179952,3077.21098765,1257.79677949,44042.5062973,1133.71422049,1497.6101044,-,-,-,-,-,317.461092224,77560.8174767
16,الربع الثالث عام 2016م\nThird quarter 2016,27417.46,2807.14,1509.39,44965.14,1167.53,1498.48,-,-,-,-,-,317.78,79682.92
17,الربع الرابع عام 2016م\nFourth quarter 2016,62300.49,2801.25,1412.66,54960.08,6207.26,658.16,-,-,-,-,-,325.54,128665.44
18,الربع الأول عام 2017م\nFirst quarter 2017,62166.0207513,2807.428865,1592.94568468,54891.9953597,6459.86557835,661.19,-,-,-,-,-,318.485174845,128897.931414
19,الربع الثاني عام 2017م\nSecond quarter 2017,77137.4548211,4138.762136,1550.34056923,56822.77,8737.87698891,669.956569825,-,-,-,-,-,321.444865589,149378.605951
20,الربع الثالث عام 2017م\nThird quarter 2017,75919.72,4489.85,1626.95,58393.93,6941.12,674.77,-,-,-,-,-,325.9,148372.24
21,الربع الرابع عام 2017م\nFourth quarter 2017,75857.11,4600.53,1674.49,57686.74,816.25,666.31,-,-,-,-,-,332.02,141633.45
22,الربع الأول عام 2018م\nFirst quarter 2018,81683.03,4648.09,1772.75,56673.95,1151.66,571.89,-,-,-,-,-,333.83,146835.2
23,الربع الثاني عام 2018م\nSecond quarter 2018,87241.1600278,4840.79254933,1879.9040905,56717.3018286,746.86723371,579.350131688,-,-,-,-,-,396.86815176,152402.244013
24,الربع الثالث عام 2018م\nThird quarter 2018,99674.6591118,4790.17981933,2160.18964905,57290.0065528,707.22593969,582.671903962,-,-,-,-,-,397.89880521,165602.831782
25,الربع الرابع عام 2018م\nFourth quarter 2018,104603.1,4847.00160756,1164.73496285,58321.42,7027.79417206,578.445343725,0,1280.51645296,-,-,-,456.484813308,178279.497352
26,الربع الأول عام 2019م\nFirst quarter 2019,122620.291142,4727.59184098,2056.5130275,52099.2120501,7403.00028479,568.8375,0,239.60637088,-,-,-,451.567655123,190166.619872
27,الربع الثاني عام 2019م\nSecond quarter 2019,122482.139848,4987.71810867,1879.39461453,58698.2194342,7637.69399755,581.147515387,0,249.191350587,-,-,-,383.935211167,196899.44008
28,الربع الثالث عام 2019م\nThird quarter 2019,108653.591253,4954.65548467,2048.082239,61340.0052916,7028.39950796,576.888293062,132.80680351,287.680524,-,-,-,383.334541761,185405.443939
29,الربع الرابع عام 2019م\nFourth quarter 2019,114501.03,5175.18,2262.26,58458.13,7836.23,325.15,59.75,459.51,-,-,-,382.74,189459.98
30,الربع الأول عام 2020م\nFirst quarter 2020,97081.7317695,5776.97693985,2038.12290354,61474.5958119,6561.55020103,324.459096262,135.36948975,730.416508961,-,-,-,-,174123.222721
31,الربع الثاني عام 2020م\nSecond quarter 2020,104359.418781,10222.0371434,1918.02462321,74006.1043075,7280.70386808,324.459096262,191.445689818,810.178851299,-,-,-,-,199112.372361
32,الربع الثالث عام 2020م\nThird quarter 2020,119296.162156,10307.7863539,2082.37287692,77616.5919898,9349.92484136,331.812897225,247.92319091,757.629,-,-,-,-,219990.203307
33,الربع الرابع عام 2020م\nFourth quarter 2020,125414.03,10708.9,2207.24,83156.98,9269.44,323.13,292.1,879.52,-,-,-,-,232251.34
34,الربع الأول عام 2021م\nFirst quarter 2021,134542.33,11594.61,2228.84,86673.25,10232.6,340.31,333.26,564.6,10523.71,333.02,0,0,257366.53
35,الربع الثاني عام 2021م\nSecond quarter 2021,151433.95,8847.18,2490.68,89073.26,9953.15,350.67,346.25,621.1,10961.02,364.93,0,0,274442.19
36,الربع الثالث عام 2021م\nThird quarter 2021,158999.14,10799.25,2552.79,89527.02,11572.44,350.67,370.19,749.93,11367.49,440.3,0,0,286729.22
37,الربع الرابع عام 2021م\nFourth quarter 2021,160141.02,11411.09,2517.56,96228.08,12039.73,353.85,405.72,794.62,12153.59,552.84,27.8,0,296625.9
38,الربع الأول عام 2022م\nFirst quarter 2022,191950.54,12670.26,2384.44,99133.29,13291.76,-,406.05,710.37,14141.82,710.45,27.8,0,335426.78
39,الربع الثاني عام 2022م\nSecond quarter 2022,170129.7,13009.68,2403.64,113178.38,14636.62,-,361.16,668.91,18198.09,1031.32,28.44,0,333645.94

In [23]:
data.dropna(subset=["Unnamed: 6"], axis=0, inplace = True)

In [24]:
data

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
5,نهاية الفترة,أسهم,أسواق نقد,عقاري,متعدد الأصول,التحوط \nوالمشتقات المالية,مغذي,تمويلي,أسهم الملكية الخاصة,رأس المال الجريء,وقفي,سلع,الإجمالي
6,End of Period,Equities,Money Markets,Real Estates,Multi-assets,Hedging and Other Derivatives,Feeder Fund,Credit Base Fund,Private equity,Venture capital,Endowment Investment,Commodities,Total
7,النصف الأول عام 2013م\nFirst half 2013,10865.07,420.39,17733.25,571.21,2323.87,-,-,-,-,-,47.85,31972.04
8,النصف الثاني عام 2013م\nSecond half 2013,11536.9,608.5,21437.2,602,2404.9,-,-,-,-,-,50.7,36644.4
9,النصف الأول عام 2014م\nFirst half 2014,13337.08,868.37,30917.56,538.94,2522.65,-,-,-,-,-,47.44,48235.07
10,النصف الثاني عام 2014م\nSecond half 2014,13667.79,1688.74,33068.11,506.48,2329.07,-,-,-,-,-,46.8,51433.2
11,النصف الأول عام 2015م\nFirst half 2015,13771.24,1783.46,35109.37,409.03,2470,-,-,-,-,-,247.11,54200.23
12,الربع الثالث عام 2015م\nThird quarter 2015,22943,1952.17,42879.45,496.33,2284.19,-,-,-,-,-,252.53,71220.05
13,الربع الرابع عام 2015م\nFourth quarter 2015,23499.24,1725.27,45466.75,1145.78,2220.22,-,-,-,-,-,252.23,77394.53
14,الربع الأول عام 2016م\nFirst quarter 2016,25845.3961622,1603.82495235,39839.564976,1114.69849421,1960.32897463,-,-,-,-,-,300.989934113,73757.5093765
15,الربع الثاني عام 2016م\nSecond quarter 2016,26234.5179952,1257.79677949,44042.5062973,1133.71422049,1497.6101044,-,-,-,-,-,317.461092224,77560.8174767
16,الربع الثالث عام 2016م\nThird quarter 2016,27417.46,1509.39,44965.14,1167.53,1498.48,-,-,-,-,-,317.78,79682.92
17,الربع الرابع عام 2016م\nFourth quarter 2016,62300.49,1412.66,54960.08,6207.26,658.16,-,-,-,-,-,325.54,128665.44
18,الربع الأول عام 2017م\nFirst quarter 2017,62166.0207513,1592.94568468,54891.9953597,6459.86557835,661.19,-,-,-,-,-,318.485174845,128897.931414
19,الربع الثاني عام 2017م\nSecond quarter 2017,77137.4548211,1550.34056923,56822.77,8737.87698891,669.956569825,-,-,-,-,-,321.444865589,149378.605951
20,الربع الثالث عام 2017م\nThird quarter 2017,75919.72,1626.95,58393.93,6941.12,674.77,-,-,-,-,-,325.9,148372.24
21,الربع الرابع عام 2017م\nFourth quarter 2017,75857.11,1674.49,57686.74,816.25,666.31,-,-,-,-,-,332.02,141633.45
22,الربع الأول عام 2018م\nFirst quarter 2018,81683.03,1772.75,56673.95,1151.66,571.89,-,-,-,-,-,333.83,146835.2
23,الربع الثاني عام 2018م\nSecond quarter 2018,87241.1600278,1879.9040905,56717.3018286,746.86723371,579.350131688,-,-,-,-,-,396.86815176,152402.244013
24,الربع الثالث عام 2018م\nThird quarter 2018,99674.6591118,2160.18964905,57290.0065528,707.22593969,582.671903962,-,-,-,-,-,397.89880521,165602.831782
25,الربع الرابع عام 2018م\nFourth quarter 2018,104603.1,1164.73496285,58321.42,7027.79417206,578.445343725,0,1280.51645296,-,-,-,456.484813308,178279.497352
26,الربع الأول عام 2019م\nFirst quarter 2019,122620.291142,2056.5130275,52099.2120501,7403.00028479,568.8375,0,239.60637088,-,-,-,451.567655123,190166.619872
27,الربع الثاني عام 2019م\nSecond quarter 2019,122482.139848,1879.39461453,58698.2194342,7637.69399755,581.147515387,0,249.191350587,-,-,-,383.935211167,196899.44008
28,الربع الثالث عام 2019م\nThird quarter 2019,108653.591253,2048.082239,61340.0052916,7028.39950796,576.888293062,132.80680351,287.680524,-,-,-,383.334541761,185405.443939
29,الربع الرابع عام 2019م\nFourth quarter 2019,114501.03,2262.26,58458.13,7836.23,325.15,59.75,459.51,-,-,-,382.74,189459.98
30,الربع الأول عام 2020م\nFirst quarter 2020,97081.7317695,2038.12290354,61474.5958119,6561.55020103,324.459096262,135.36948975,730.416508961,-,-,-,-,174123.222721
31,الربع الثاني عام 2020م\nSecond quarter 2020,104359.418781,1918.02462321,74006.1043075,7280.70386808,324.459096262,191.445689818,810.178851299,-,-,-,-,199112.372361
32,الربع الثالث عام 2020م\nThird quarter 2020,119296.162156,2082.37287692,77616.5919898,9349.92484136,331.812897225,247.92319091,757.629,-,-,-,-,219990.203307
33,الربع الرابع عام 2020م\nFourth quarter 2020,125414.03,2207.24,83156.98,9269.44,323.13,292.1,879.52,-,-,-,-,232251.34
34,الربع الأول عام 2021م\nFirst quarter 2021,134542.33,2228.84,86673.25,10232.6,340.31,333.26,564.6,10523.71,333.02,0,0,257366.53
35,الربع الثاني عام 2021م\nSecond quarter 2021,151433.95,2490.68,89073.26,9953.15,350.67,346.25,621.1,10961.02,364.93,0,0,274442.19
36,الربع الثالث عام 2021م\nThird quarter 2021,158999.14,2552.79,89527.02,11572.44,350.67,370.19,749.93,11367.49,440.3,0,0,286729.22
37,الربع الرابع عام 2021م\nFourth quarter 2021,160141.02,2517.56,96228.08,12039.73,353.85,405.72,794.62,12153.59,552.84,27.8,0,296625.9
38,الربع الأول عام 2022م\nFirst quarter 2022,191950.54,2384.44,99133.29,13291.76,-,406.05,710.37,14141.82,710.45,27.8,0,335426.78
39,الربع الثاني عام 2022م\nSecond quarter 2022,170129.7,2403.64,113178.38,14636.62,-,361.16,668.91,18198.09,1031.32,28.44,0,333645.94